- name: create CA certificate directory
  file: path=/etc/ssh/CA state=directory owner=root group=root mode=0700

- name: create CA certificate
  shell: echo 'y' | ssh-keygen -t rsa -N '' -b 4096 -f /etc/ssh/CA/host-ca

- name: create CA certificate
  shell: echo 'y' | ssh-keygen -t rsa -N '' -b 4096 -f /etc/ssh/CA/client-ca

- name: download public CA key
  fetch: src=/etc/ssh/CA/client-ca.pub dest={{ ansible_temp_directory }}/client-ca.pub flat=yes
